---
version: "2"

services:
  our-app:
    build: .
    environment:
      - MODE=dev
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
    ports:
      - "9090:9090"
      
  rabbitmq:
    image: rabbitmq:3.6.1-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "8023:15672"
      - "8024:5672"