swagger: "2.0"

info:
  title: "My first API"
  version: "1.0"

paths:
  /zips/:
    get:
      responses:
        '200':
          description: 'Fetch a list of zip codes'
          schema:
            type: array
            items:
              $ref: '#/definitions/Item'
    put:
      operationId: api.zips.put_zip
      parameters:
        - name: item
          in: body
          schema:
            $ref: '#/definitions/Item'
      responses:
        200:
          description: Zip logged
        201:
          description: Zip exists
  /items/:
    get:
      responses:
        '200':
          description: 'Fetch weather'
          schema:
            type: array
            items:
              $ref: '#/definitions/Item'
    put:
      operationId: api.items.put_weather
      parameters:
        - name: item
          in: body
          schema:
            $ref: '#/definitions/Item'
      responses:
        200:
          description: Weather logged

definitions:
  Item:
    type: object
    required:
      - zip_code
    properties:
      zip_code:
        type: string